/** Rutas MVP alineadas a backend/config/paqsuite_mvp.php */
export const mvpMenuRoutePaths = [
  '/pedidos/carga',
  '/pedidos/importacion-masiva',
  '/presupuestos/ingresados',
  '/pedidos/ingresados',
  '/pedidos/pendientes',
  '/pedidos/detalle',
  '/consultas/deuda',
  '/consultas/cheques',
  '/consultas/historial',
  '/consultas/stock',
  '/presupuestos/tratativas',
  '/dashboard',
  '/integracion/logs',
  '/general/parametros',
  '/excel-import/historial',
  '/excel-import/procesos/:codigoProceso',
  '/excel-import/lotes/:guidImportacion',
] as const;
