<?php

return [

    'gridLayoutsEnabled' => true,

    'pivotsEnabled' => (bool) env('PIVOTS_ENABLED', false),

    'pivotLayoutsEnabled' => (bool) env('PIVOT_LAYOUTS_ENABLED', false),

    'menuItems' => [
        ['menuKey' => 'grupoPedidos', 'procedimiento' => 'grp_pedidos', 'text' => 'Pedidos', 'orden' => 10, 'tipoProceso' => 'G'],
        ['menuKey' => 'cargaPedidosPresupuestos', 'procedimiento' => 'pw_cargapedidos', 'text' => 'Carga de Pedidos', 'orden' => 11, 'routeName' => '/pedidos/carga', 'parentProcedimiento' => 'grp_pedidos'],
        ['menuKey' => 'presupuestosIngresados', 'procedimiento' => 'pw_presupuestosingresados', 'text' => 'Presupuestos Ingresados', 'orden' => 12, 'routeName' => '/presupuestos/ingresados', 'parentProcedimiento' => 'grp_pedidos'],
        ['menuKey' => 'pedidosIngresados', 'procedimiento' => 'pw_pedidosingresados', 'text' => 'Pedidos Ingresados', 'orden' => 13, 'routeName' => '/pedidos/ingresados', 'parentProcedimiento' => 'grp_pedidos'],
        ['menuKey' => 'pedidosPendientes', 'procedimiento' => 'pw_pedidospendientes', 'text' => 'Pedidos Pendientes', 'orden' => 14, 'routeName' => '/pedidos/pendientes', 'parentProcedimiento' => 'grp_pedidos'],
        ['menuKey' => 'detallePedidos', 'procedimiento' => 'pw_detallepedidos', 'text' => 'Detalle de pedidos', 'orden' => 15, 'routeName' => '/pedidos/detalle', 'parentProcedimiento' => 'grp_pedidos'],
        ['menuKey' => 'grupoGeneral', 'procedimiento' => 'grp_general', 'text' => 'General', 'orden' => 60, 'tipoProceso' => 'G'],
        ['menuKey' => 'consultaParametros', 'procedimiento' => 'pw_consultaparametros', 'text' => 'Consulta de parametros', 'orden' => 61, 'routeName' => '/general/parametros', 'parentProcedimiento' => 'grp_general'],
        ['menuKey' => 'grupoInformes', 'procedimiento' => 'grp_informes', 'text' => 'Informes', 'orden' => 20, 'tipoProceso' => 'G'],
        ['menuKey' => 'deudaClientes', 'procedimiento' => 'pw_deudaclientes', 'text' => 'Deudas', 'orden' => 21, 'routeName' => '/consultas/deuda', 'parentProcedimiento' => 'grp_informes'],
        ['menuKey' => 'chequesCartera', 'procedimiento' => 'pw_consultacheques', 'text' => 'Cheques', 'orden' => 22, 'routeName' => '/consultas/cheques', 'parentProcedimiento' => 'grp_informes'],
        ['menuKey' => 'historialVentas', 'procedimiento' => 'pw_historialventas', 'text' => 'Historial Ventas', 'orden' => 23, 'routeName' => '/consultas/historial', 'parentProcedimiento' => 'grp_informes', 'tipoProceso' => 'informe'],
        ['menuKey' => 'stock', 'procedimiento' => 'pw_consultastock', 'text' => 'Stock', 'orden' => 24, 'routeName' => '/consultas/stock', 'parentProcedimiento' => 'grp_informes'],
        ['menuKey' => 'grupoGestionPresupuestos', 'procedimiento' => 'grp_gestion_presupuestos', 'text' => 'Gestion Presupuestos', 'orden' => 30, 'tipoProceso' => 'G'],
        ['menuKey' => 'tratativasPresupuestos', 'procedimiento' => 'pw_tratativaspresup', 'text' => 'Tratativas Presupuestos', 'orden' => 31, 'routeName' => '/presupuestos/tratativas', 'parentProcedimiento' => 'grp_gestion_presupuestos'],
        ['menuKey' => 'dashboard', 'procedimiento' => 'pw_dashboard', 'text' => 'Dashboard', 'orden' => 40, 'routeName' => '/dashboard'],
        ['menuKey' => 'logsIntegracion', 'procedimiento' => 'pw_logsintegracion', 'text' => 'Logs Integracion', 'orden' => 50, 'routeName' => '/integracion/logs'],
    ],

    'roles' => [
        [
            'nombreRol' => 'Cliente',
            'descripcionRol' => 'Perfil cliente MVP',
            'accesoTotal' => false,
        ],
        [
            'nombreRol' => 'Vendedor',
            'descripcionRol' => 'Perfil vendedor MVP',
            'accesoTotal' => false,
        ],
        [
            'nombreRol' => 'VendedorAcotado',
            'descripcionRol' => 'Vendedor MVP con menu acotado (seed)',
            'accesoTotal' => false,
        ],
        [
            'nombreRol' => 'Supervisor',
            'descripcionRol' => 'Perfil supervisor MVP',
            'accesoTotal' => true,
        ],
    ],

    'vendedorAcotadoProcedimientos' => [
        'pw_cargapedidos',
        'pw_presupuestosingresados',
        'pw_pedidosingresados',
        'pw_dashboard',
    ],

    'visibilityProcedimientosByRole' => [
        'Cliente' => [
            'pw_clientes_visibles',
            'pw_comprobantes_visibles',
            'pw_dashboard',
        ],
        'Vendedor' => [
            'pw_clientes_visibles',
            'pw_comprobantes_visibles',
            'pw_dashboard',
        ],
        'VendedorAcotado' => [
            'pw_clientes_visibles',
            'pw_comprobantes_visibles',
            'pw_dashboard',
        ],
    ],

    'users' => [
        [
            'codigo' => 'cliente.mvp',
            'name' => 'Cliente MVP',
            'email' => 'cliente.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'CLIMVP001',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es-AR',
            'theme' => 'light',
        ],
        [
            'codigo' => 'vendedor.acotado.mvp',
            'name' => 'Vendedor Acotado MVP',
            'email' => 'vendedor.acotado.mvp@paqsuite.local',
            'rol' => 'VendedorAcotado',
            'hasPermiso' => true,
            'codLogin' => 'VENACOT01',
            'commercialTable' => 'vendedor',
            'supervisor' => false,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es-AR',
            'theme' => 'light',
            'rolAtributos' => 'acotado',
        ],
        [
            'codigo' => 'supervisor.mvp',
            'name' => 'Supervisor MVP',
            'email' => 'supervisor.mvp@paqsuite.local',
            'rol' => 'Supervisor',
            'hasPermiso' => true,
            'codLogin' => 'VENSUP01',
            'commercialTable' => 'vendedor',
            'supervisor' => true,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es-AR',
            'theme' => 'light',
        ],
        [
            'codigo' => 'usuario.sinPermiso.mvp',
            'name' => 'Usuario Sin Permiso MVP',
            'email' => 'usuario.sinpermiso.mvp@paqsuite.local',
            'rol' => null,
            'hasPermiso' => false,
            'codLogin' => null,
            'commercialTable' => null,
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es-AR',
            'theme' => 'light',
        ],
        [
            'codigo' => 'usuario.sinVinculo.mvp',
            'name' => 'Usuario Sin Vinculo MVP',
            'email' => 'usuario.sinvinculo.mvp@paqsuite.local',
            'rol' => 'Vendedor',
            'hasPermiso' => true,
            'codLogin' => null,
            'commercialTable' => null,
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es-AR',
            'theme' => 'light',
        ],
        [
            'codigo' => 'usuario.perfilAmbiguo.mvp',
            'name' => 'Usuario Perfil Ambiguo MVP',
            'email' => 'usuario.perfilambiguo.mvp@paqsuite.local',
            'rol' => 'Vendedor',
            'hasPermiso' => true,
            'codLogin' => 'AMBIG01',
            'commercialTable' => null,
            'commercialDualLink' => true,
            'supervisor' => false,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es-AR',
            'theme' => 'light',
        ],
        [
            'codigo' => 'vendedor.sinMenu.mvp',
            'name' => 'Vendedor Sin Menu MVP',
            'email' => 'vendedor.sinmenu.mvp@paqsuite.local',
            'rol' => 'Vendedor',
            'hasPermiso' => true,
            'codLogin' => 'VENSINM01',
            'commercialTable' => 'vendedor',
            'supervisor' => false,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es-AR',
            'theme' => 'light',
            'rolAtributos' => 'none',
        ],
        [
            'codigo' => 'primerIngreso.mvp',
            'name' => 'Primer Ingreso MVP',
            'email' => 'primerIngreso.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'PRIMVP001',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => true,
            'locale' => 'es-AR',
            'theme' => 'light',
        ],
        [
            'codigo' => 'cambioClave.mvp',
            'name' => 'Cambio Clave MVP',
            'email' => 'cambioClave.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'CAMBIOCL01',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es',
            'theme' => 'light',
        ],
        [
            'codigo' => 'locale.en.mvp',
            'name' => 'Locale EN MVP',
            'email' => 'locale.en.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'LOCEN001',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'en',
            'theme' => 'light',
        ],
        [
            'codigo' => 'locale.it.mvp',
            'name' => 'Locale IT MVP',
            'email' => 'locale.it.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'LOCIT001',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'it',
            'theme' => 'light',
        ],
        [
            'codigo' => 'locale.null.mvp',
            'name' => 'Locale Null MVP',
            'email' => 'locale.null.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'LOCNULL01',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => null,
            'theme' => 'light',
        ],
        [
            'codigo' => 'locale.invalid.mvp',
            'name' => 'Locale Invalid MVP',
            'email' => 'locale.invalid.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'LOCINV01',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'xx',
            'theme' => 'light',
        ],
        [
            'codigo' => 'openTab.true.mvp',
            'name' => 'Open Tab True MVP',
            'email' => 'openTab.true.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'OPENTABT01',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es',
            'theme' => 'light',
            'openInNewTab' => true,
        ],
        [
            'codigo' => 'openTab.false.mvp',
            'name' => 'Open Tab False MVP',
            'email' => 'openTab.false.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'OPENTABF01',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es',
            'theme' => 'light',
            'openInNewTab' => false,
        ],
        [
            'codigo' => 'openTab.null.mvp',
            'name' => 'Open Tab Null MVP',
            'email' => 'openTab.null.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'OPENTABN01',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es',
            'theme' => 'light',
            'openInNewTab' => null,
        ],
        [
            'codigo' => 'theme.null.mvp',
            'name' => 'Theme Null MVP',
            'email' => 'theme.null.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'THEMNULL01',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es',
            // Columna users.theme NOT NULL: cadena vacía simula ausencia de preferencia.
            'theme' => '',
        ],
        [
            'codigo' => 'theme.light.mvp',
            'name' => 'Theme Light MVP',
            'email' => 'theme.light.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'THEMLGT01',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es',
            'theme' => 'light',
        ],
        [
            'codigo' => 'theme.dark.mvp',
            'name' => 'Theme Dark MVP',
            'email' => 'theme.dark.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'THEMDRK01',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es',
            'theme' => 'generic.dark',
        ],
        [
            'codigo' => 'theme.invalid.mvp',
            'name' => 'Theme Invalid MVP',
            'email' => 'theme.invalid.mvp@paqsuite.local',
            'rol' => 'Cliente',
            'hasPermiso' => true,
            'codLogin' => 'THEMINV01',
            'commercialTable' => 'cliente',
            'supervisor' => null,
            'activo' => true,
            'inhabilitado' => false,
            'firstLogin' => false,
            'locale' => 'es',
            'theme' => 'xx',
        ],
    ],

];
