<?php

return [
    'default' => 'generic.light',

    'supported' => [
        'default',
        'light',
        'dark',
        'light.compact',
        'dark.compact',
        'carmine',
        'carmine.compact',
        'darkmoon',
        'darkmoon.compact',
        'darkviolet',
        'darkviolet.compact',
        'greenmist',
        'greenmist.compact',
        'softblue',
        'softblue.compact',
        'contrast',
        'contrast.compact',
        'generic.light',
        'generic.dark',
        'material.blue.light',
        'material.blue.dark',
        'material.blue.light.compact',
        'material.blue.dark.compact',
        'material.orange.light',
        'material.orange.dark',
        'material.orange.light.compact',
        'material.orange.dark.compact',
        'material.lime.light',
        'material.lime.dark',
        'material.lime.light.compact',
        'material.lime.dark.compact',
        'material.purple.light',
        'material.purple.dark',
        'material.purple.light.compact',
        'material.purple.dark.compact',
        'material.teal.light',
        'material.teal.dark',
        'material.teal.light.compact',
        'material.teal.dark.compact',
        'fluent.blue.light',
        'fluent.blue.dark',
        'fluent.blue.light.compact',
        'fluent.blue.dark.compact',
        'fluent.saas.light',
        'fluent.saas.dark',
        'fluent.saas.light.compact',
        'fluent.saas.dark.compact',
    ],

    'legacyAliases' => [
        'default' => 'generic.light',
        'light' => 'generic.light',
        'dark' => 'generic.dark',
    ],
];
