export const defaultThemeKey = 'generic.light';

export const supportedThemeKeys = [
  'default',
  'light',
  'dark',
  'generic.light',
  'generic.dark',
  'light.compact',
  'dark.compact',
  'carmine',
  'carmine.compact',
  'darkmoon',
  'darkmoon.compact',
  'darkviolet',
  'darkviolet.compact',
  'greenmist',
  'greenmist.compact',
  'softblue',
  'softblue.compact',
  'contrast',
  'contrast.compact',
  'material.blue.light',
  'material.blue.dark',
  'material.blue.light.compact',
  'material.blue.dark.compact',
  'material.orange.light',
  'material.orange.dark',
  'material.orange.light.compact',
  'material.orange.dark.compact',
  'material.lime.light',
  'material.lime.dark',
  'material.lime.light.compact',
  'material.lime.dark.compact',
  'material.purple.light',
  'material.purple.dark',
  'material.purple.light.compact',
  'material.purple.dark.compact',
  'material.teal.light',
  'material.teal.dark',
  'material.teal.light.compact',
  'material.teal.dark.compact',
  'fluent.blue.light',
  'fluent.blue.dark',
  'fluent.blue.light.compact',
  'fluent.blue.dark.compact',
  'fluent.saas.light',
  'fluent.saas.dark',
  'fluent.saas.light.compact',
  'fluent.saas.dark.compact',
] as const;

export type SupportedThemeKey = (typeof supportedThemeKeys)[number];

type SupportedThemeLocale = 'es' | 'en' | 'it' | 'pt' | 'fr';

const themeLabelsByLocale: Record<SupportedThemeLocale, Record<SupportedThemeKey, string>> = {
  es: {
    default: 'Predeterminado',
    light: 'Light',
    dark: 'Dark',
    'generic.light': 'Generic Claro',
    'generic.dark': 'Generic Oscuro',
    'light.compact': 'Light Compacto',
    'dark.compact': 'Dark Compacto',
    carmine: 'Carmine',
    'carmine.compact': 'Carmine Compacto',
    darkmoon: 'DarkMoon',
    'darkmoon.compact': 'DarkMoon Compacto',
    darkviolet: 'Dark Violet',
    'darkviolet.compact': 'Dark Violet Compacto',
    greenmist: 'Green Mist',
    'greenmist.compact': 'Green Mist Compacto',
    softblue: 'Soft Blue',
    'softblue.compact': 'Soft Blue Compacto',
    contrast: 'Contrast',
    'contrast.compact': 'Contrast Compacto',
    'material.blue.light': 'Material Azul Claro',
    'material.blue.dark': 'Material Azul Oscuro',
    'material.blue.light.compact': 'Material Azul Claro Compacto',
    'material.blue.dark.compact': 'Material Azul Oscuro Compacto',
    'material.orange.light': 'Material Naranja Claro',
    'material.orange.dark': 'Material Naranja Oscuro',
    'material.orange.light.compact': 'Material Naranja Claro Compacto',
    'material.orange.dark.compact': 'Material Naranja Oscuro Compacto',
    'material.lime.light': 'Material Lima Claro',
    'material.lime.dark': 'Material Lima Oscuro',
    'material.lime.light.compact': 'Material Lima Claro Compacto',
    'material.lime.dark.compact': 'Material Lima Oscuro Compacto',
    'material.purple.light': 'Material Purpura Claro',
    'material.purple.dark': 'Material Purpura Oscuro',
    'material.purple.light.compact': 'Material Purpura Claro Compacto',
    'material.purple.dark.compact': 'Material Purpura Oscuro Compacto',
    'material.teal.light': 'Material Teal Claro',
    'material.teal.dark': 'Material Teal Oscuro',
    'material.teal.light.compact': 'Material Teal Claro Compacto',
    'material.teal.dark.compact': 'Material Teal Oscuro Compacto',
    'fluent.blue.light': 'Fluent Azul Claro',
    'fluent.blue.dark': 'Fluent Azul Oscuro',
    'fluent.blue.light.compact': 'Fluent Azul Claro Compacto',
    'fluent.blue.dark.compact': 'Fluent Azul Oscuro Compacto',
    'fluent.saas.light': 'Fluent SaaS Claro',
    'fluent.saas.dark': 'Fluent SaaS Oscuro',
    'fluent.saas.light.compact': 'Fluent SaaS Claro Compacto',
    'fluent.saas.dark.compact': 'Fluent SaaS Oscuro Compacto',
  },
  en: {
    default: 'Default',
    light: 'Light',
    dark: 'Dark',
    'generic.light': 'Generic Light',
    'generic.dark': 'Generic Dark',
    'light.compact': 'Light Compact',
    'dark.compact': 'Dark Compact',
    carmine: 'Carmine',
    'carmine.compact': 'Carmine Compact',
    darkmoon: 'DarkMoon',
    'darkmoon.compact': 'DarkMoon Compact',
    darkviolet: 'Dark Violet',
    'darkviolet.compact': 'Dark Violet Compact',
    greenmist: 'Green Mist',
    'greenmist.compact': 'Green Mist Compact',
    softblue: 'Soft Blue',
    'softblue.compact': 'Soft Blue Compact',
    contrast: 'Contrast',
    'contrast.compact': 'Contrast Compact',
    'material.blue.light': 'Material Blue Light',
    'material.blue.dark': 'Material Blue Dark',
    'material.blue.light.compact': 'Material Blue Light Compact',
    'material.blue.dark.compact': 'Material Blue Dark Compact',
    'material.orange.light': 'Material Orange Light',
    'material.orange.dark': 'Material Orange Dark',
    'material.orange.light.compact': 'Material Orange Light Compact',
    'material.orange.dark.compact': 'Material Orange Dark Compact',
    'material.lime.light': 'Material Lime Light',
    'material.lime.dark': 'Material Lime Dark',
    'material.lime.light.compact': 'Material Lime Light Compact',
    'material.lime.dark.compact': 'Material Lime Dark Compact',
    'material.purple.light': 'Material Purple Light',
    'material.purple.dark': 'Material Purple Dark',
    'material.purple.light.compact': 'Material Purple Light Compact',
    'material.purple.dark.compact': 'Material Purple Dark Compact',
    'material.teal.light': 'Material Teal Light',
    'material.teal.dark': 'Material Teal Dark',
    'material.teal.light.compact': 'Material Teal Light Compact',
    'material.teal.dark.compact': 'Material Teal Dark Compact',
    'fluent.blue.light': 'Fluent Blue Light',
    'fluent.blue.dark': 'Fluent Blue Dark',
    'fluent.blue.light.compact': 'Fluent Blue Light Compact',
    'fluent.blue.dark.compact': 'Fluent Blue Dark Compact',
    'fluent.saas.light': 'Fluent SaaS Light',
    'fluent.saas.dark': 'Fluent SaaS Dark',
    'fluent.saas.light.compact': 'Fluent SaaS Light Compact',
    'fluent.saas.dark.compact': 'Fluent SaaS Dark Compact',
  },
  it: {
    default: 'Predefinito',
    light: 'Light',
    dark: 'Dark',
    'generic.light': 'Generic Chiaro',
    'generic.dark': 'Generic Scuro',
    'light.compact': 'Light Compatto',
    'dark.compact': 'Dark Compatto',
    carmine: 'Carmine',
    'carmine.compact': 'Carmine Compatto',
    darkmoon: 'DarkMoon',
    'darkmoon.compact': 'DarkMoon Compatto',
    darkviolet: 'Dark Violet',
    'darkviolet.compact': 'Dark Violet Compatto',
    greenmist: 'Green Mist',
    'greenmist.compact': 'Green Mist Compatto',
    softblue: 'Soft Blue',
    'softblue.compact': 'Soft Blue Compatto',
    contrast: 'Contrast',
    'contrast.compact': 'Contrast Compatto',
    'material.blue.light': 'Material Blu Chiaro',
    'material.blue.dark': 'Material Blu Scuro',
    'material.blue.light.compact': 'Material Blu Chiaro Compatto',
    'material.blue.dark.compact': 'Material Blu Scuro Compatto',
    'material.orange.light': 'Material Arancione Chiaro',
    'material.orange.dark': 'Material Arancione Scuro',
    'material.orange.light.compact': 'Material Arancione Chiaro Compatto',
    'material.orange.dark.compact': 'Material Arancione Scuro Compatto',
    'material.lime.light': 'Material Lime Chiaro',
    'material.lime.dark': 'Material Lime Scuro',
    'material.lime.light.compact': 'Material Lime Chiaro Compatto',
    'material.lime.dark.compact': 'Material Lime Scuro Compatto',
    'material.purple.light': 'Material Viola Chiaro',
    'material.purple.dark': 'Material Viola Scuro',
    'material.purple.light.compact': 'Material Viola Chiaro Compatto',
    'material.purple.dark.compact': 'Material Viola Scuro Compatto',
    'material.teal.light': 'Material Teal Chiaro',
    'material.teal.dark': 'Material Teal Scuro',
    'material.teal.light.compact': 'Material Teal Chiaro Compatto',
    'material.teal.dark.compact': 'Material Teal Scuro Compatto',
    'fluent.blue.light': 'Fluent Blu Chiaro',
    'fluent.blue.dark': 'Fluent Blu Scuro',
    'fluent.blue.light.compact': 'Fluent Blu Chiaro Compatto',
    'fluent.blue.dark.compact': 'Fluent Blu Scuro Compatto',
    'fluent.saas.light': 'Fluent SaaS Chiaro',
    'fluent.saas.dark': 'Fluent SaaS Scuro',
    'fluent.saas.light.compact': 'Fluent SaaS Chiaro Compatto',
    'fluent.saas.dark.compact': 'Fluent SaaS Scuro Compatto',
  },
  pt: {
    default: 'Padrao',
    light: 'Light',
    dark: 'Dark',
    'generic.light': 'Generic Claro',
    'generic.dark': 'Generic Escuro',
    'light.compact': 'Light Compacto',
    'dark.compact': 'Dark Compacto',
    carmine: 'Carmine',
    'carmine.compact': 'Carmine Compacto',
    darkmoon: 'DarkMoon',
    'darkmoon.compact': 'DarkMoon Compacto',
    darkviolet: 'Dark Violet',
    'darkviolet.compact': 'Dark Violet Compacto',
    greenmist: 'Green Mist',
    'greenmist.compact': 'Green Mist Compacto',
    softblue: 'Soft Blue',
    'softblue.compact': 'Soft Blue Compacto',
    contrast: 'Contrast',
    'contrast.compact': 'Contrast Compacto',
    'material.blue.light': 'Material Azul Claro',
    'material.blue.dark': 'Material Azul Escuro',
    'material.blue.light.compact': 'Material Azul Claro Compacto',
    'material.blue.dark.compact': 'Material Azul Escuro Compacto',
    'material.orange.light': 'Material Laranja Claro',
    'material.orange.dark': 'Material Laranja Escuro',
    'material.orange.light.compact': 'Material Laranja Claro Compacto',
    'material.orange.dark.compact': 'Material Laranja Escuro Compacto',
    'material.lime.light': 'Material Lima Claro',
    'material.lime.dark': 'Material Lima Escuro',
    'material.lime.light.compact': 'Material Lima Claro Compacto',
    'material.lime.dark.compact': 'Material Lima Escuro Compacto',
    'material.purple.light': 'Material Roxo Claro',
    'material.purple.dark': 'Material Roxo Escuro',
    'material.purple.light.compact': 'Material Roxo Claro Compacto',
    'material.purple.dark.compact': 'Material Roxo Escuro Compacto',
    'material.teal.light': 'Material Teal Claro',
    'material.teal.dark': 'Material Teal Escuro',
    'material.teal.light.compact': 'Material Teal Claro Compacto',
    'material.teal.dark.compact': 'Material Teal Escuro Compacto',
    'fluent.blue.light': 'Fluent Azul Claro',
    'fluent.blue.dark': 'Fluent Azul Escuro',
    'fluent.blue.light.compact': 'Fluent Azul Claro Compacto',
    'fluent.blue.dark.compact': 'Fluent Azul Escuro Compacto',
    'fluent.saas.light': 'Fluent SaaS Claro',
    'fluent.saas.dark': 'Fluent SaaS Escuro',
    'fluent.saas.light.compact': 'Fluent SaaS Claro Compacto',
    'fluent.saas.dark.compact': 'Fluent SaaS Escuro Compacto',
  },
  fr: {
    default: 'Par defaut',
    light: 'Light',
    dark: 'Dark',
    'generic.light': 'Generic Clair',
    'generic.dark': 'Generic Sombre',
    'light.compact': 'Light Compact',
    'dark.compact': 'Dark Compact',
    carmine: 'Carmine',
    'carmine.compact': 'Carmine Compact',
    darkmoon: 'DarkMoon',
    'darkmoon.compact': 'DarkMoon Compact',
    darkviolet: 'Dark Violet',
    'darkviolet.compact': 'Dark Violet Compact',
    greenmist: 'Green Mist',
    'greenmist.compact': 'Green Mist Compact',
    softblue: 'Soft Blue',
    'softblue.compact': 'Soft Blue Compact',
    contrast: 'Contrast',
    'contrast.compact': 'Contrast Compact',
    'material.blue.light': 'Material Bleu Clair',
    'material.blue.dark': 'Material Bleu Sombre',
    'material.blue.light.compact': 'Material Bleu Clair Compact',
    'material.blue.dark.compact': 'Material Bleu Sombre Compact',
    'material.orange.light': 'Material Orange Clair',
    'material.orange.dark': 'Material Orange Sombre',
    'material.orange.light.compact': 'Material Orange Clair Compact',
    'material.orange.dark.compact': 'Material Orange Sombre Compact',
    'material.lime.light': 'Material Lime Clair',
    'material.lime.dark': 'Material Lime Sombre',
    'material.lime.light.compact': 'Material Lime Clair Compact',
    'material.lime.dark.compact': 'Material Lime Sombre Compact',
    'material.purple.light': 'Material Violet Clair',
    'material.purple.dark': 'Material Violet Sombre',
    'material.purple.light.compact': 'Material Violet Clair Compact',
    'material.purple.dark.compact': 'Material Violet Sombre Compact',
    'material.teal.light': 'Material Teal Clair',
    'material.teal.dark': 'Material Teal Sombre',
    'material.teal.light.compact': 'Material Teal Clair Compact',
    'material.teal.dark.compact': 'Material Teal Sombre Compact',
    'fluent.blue.light': 'Fluent Bleu Clair',
    'fluent.blue.dark': 'Fluent Bleu Sombre',
    'fluent.blue.light.compact': 'Fluent Bleu Clair Compact',
    'fluent.blue.dark.compact': 'Fluent Bleu Sombre Compact',
    'fluent.saas.light': 'Fluent SaaS Clair',
    'fluent.saas.dark': 'Fluent SaaS Sombre',
    'fluent.saas.light.compact': 'Fluent SaaS Clair Compact',
    'fluent.saas.dark.compact': 'Fluent SaaS Sombre Compact',
  },
};

export function isSupportedThemeKey(value: string): value is SupportedThemeKey {
  return (supportedThemeKeys as readonly string[]).includes(value);
}

function resolveThemeLocale(locale: string): SupportedThemeLocale {
  const normalizedLocale = locale.trim().toLowerCase();

  if (normalizedLocale.startsWith('en')) {
    return 'en';
  }
  if (normalizedLocale.startsWith('it')) {
    return 'it';
  }
  if (normalizedLocale.startsWith('pt')) {
    return 'pt';
  }
  if (normalizedLocale.startsWith('fr')) {
    return 'fr';
  }

  return 'es';
}

export function themeDisplayLabel(themeKey: SupportedThemeKey, locale: string): string {
  return themeLabelsByLocale[resolveThemeLocale(locale)][themeKey];
}
